---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sshd
  name: ssh
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: sshd
  sessionAffinity: None
  type: NodePort
